
# cargo-vet config file

[cargo-vet]
version = "0.10"

[policy.libloadorder]
audit-as-crates-io = false

[[exemptions.aho-corasick]]
version = "1.1.3"
criteria = "safe-to-run"

[[exemptions.anes]]
version = "0.1.6"
criteria = "safe-to-run"

[[exemptions.anstyle]]
version = "1.0.10"
criteria = "safe-to-run"

[[exemptions.autocfg]]
version = "1.4.0"
criteria = "safe-to-run"

[[exemptions.bitflags]]
version = "2.9.0"
criteria = "safe-to-deploy"

[[exemptions.block-buffer]]
version = "0.10.4"
criteria = "safe-to-deploy"

[[exemptions.bumpalo]]
version = "3.17.0"
criteria = "safe-to-run"

[[exemptions.cast]]
version = "0.3.0"
criteria = "safe-to-run"

[[exemptions.cfg-if]]
version = "1.0.0"
criteria = "safe-to-deploy"

[[exemptions.ciborium]]
version = "0.2.2"
criteria = "safe-to-run"

[[exemptions.ciborium-io]]
version = "0.2.2"
criteria = "safe-to-run"

[[exemptions.ciborium-ll]]
version = "0.2.2"
criteria = "safe-to-run"

[[exemptions.clap]]
version = "4.5.37"
criteria = "safe-to-run"

[[exemptions.clap_builder]]
version = "4.5.37"
criteria = "safe-to-run"

[[exemptions.clap_lex]]
version = "0.7.4"
criteria = "safe-to-run"

[[exemptions.const-random]]
version = "0.1.18"
criteria = "safe-to-deploy"

[[exemptions.const-random-macro]]
version = "0.1.16"
criteria = "safe-to-deploy"

[[exemptions.cpufeatures]]
version = "0.2.17"
criteria = "safe-to-deploy"

[[exemptions.criterion]]
version = "0.7.0"
criteria = "safe-to-run"

[[exemptions.criterion-plot]]
version = "0.6.0"
criteria = "safe-to-run"

[[exemptions.crossbeam-deque]]
version = "0.8.6"
criteria = "safe-to-deploy"

[[exemptions.crossbeam-epoch]]
version = "0.9.18"
criteria = "safe-to-deploy"

[[exemptions.crossbeam-utils]]
version = "0.8.21"
criteria = "safe-to-deploy"

[[exemptions.crunchy]]
version = "0.2.3"
criteria = "safe-to-deploy"

[[exemptions.crypto-common]]
version = "0.1.6"
criteria = "safe-to-deploy"

[[exemptions.digest]]
version = "0.10.7"
criteria = "safe-to-deploy"

[[exemptions.dirs]]
version = "6.0.0"
criteria = "safe-to-deploy"

[[exemptions.dirs-sys]]
version = "0.5.0"
criteria = "safe-to-deploy"

[[exemptions.dlv-list]]
version = "0.5.2"
criteria = "safe-to-deploy"

[[exemptions.either]]
version = "1.15.0"
criteria = "safe-to-deploy"

[[exemptions.encoding_rs]]
version = "0.8.35"
criteria = "safe-to-deploy"

[[exemptions.errno]]
version = "0.3.11"
criteria = "safe-to-run"

[[exemptions.esplugin]]
version = "6.1.3"
criteria = "safe-to-deploy"

[[exemptions.fastrand]]
version = "2.3.0"
criteria = "safe-to-run"

[[exemptions.generic-array]]
version = "0.14.7"
criteria = "safe-to-deploy"

[[exemptions.getrandom]]
version = "0.2.16"
criteria = "safe-to-deploy"

[[exemptions.getrandom]]
version = "0.3.2"
criteria = "safe-to-run"

[[exemptions.half]]
version = "2.6.0"
criteria = "safe-to-run"

[[exemptions.hashbrown]]
version = "0.14.5"
criteria = "safe-to-deploy"

[[exemptions.itertools]]
version = "0.13.0"
criteria = "safe-to-run"

[[exemptions.itoa]]
version = "1.0.15"
criteria = "safe-to-run"

[[exemptions.js-sys]]
version = "0.3.77"
criteria = "safe-to-run"

[[exemptions.keyvalues-parser]]
version = "0.2.0"
criteria = "safe-to-deploy"

[[exemptions.libc]]
version = "0.2.175"
criteria = "safe-to-deploy"

[[exemptions.libredox]]
version = "0.1.3"
criteria = "safe-to-deploy"

[[exemptions.linux-raw-sys]]
version = "0.9.4"
criteria = "safe-to-run"

[[exemptions.log]]
version = "0.4.27"
criteria = "safe-to-run"

[[exemptions.memchr]]
version = "2.7.4"
criteria = "safe-to-deploy"

[[exemptions.nom]]
version = "8.0.0"
criteria = "safe-to-deploy"

[[exemptions.num-traits]]
version = "0.2.19"
criteria = "safe-to-run"

[[exemptions.once_cell]]
version = "1.21.3"
criteria = "safe-to-deploy"

[[exemptions.oorandom]]
version = "11.1.5"
criteria = "safe-to-run"

[[exemptions.option-ext]]
version = "0.2.0"
criteria = "safe-to-deploy"

[[exemptions.ordered-multimap]]
version = "0.7.3"
criteria = "safe-to-deploy"

[[exemptions.pest]]
version = "2.8.0"
criteria = "safe-to-deploy"

[[exemptions.pest_derive]]
version = "2.8.0"
criteria = "safe-to-deploy"

[[exemptions.pest_generator]]
version = "2.8.0"
criteria = "safe-to-deploy"

[[exemptions.pest_meta]]
version = "2.8.0"
criteria = "safe-to-deploy"

[[exemptions.plotters]]
version = "0.3.7"
criteria = "safe-to-run"

[[exemptions.plotters-backend]]
version = "0.3.7"
criteria = "safe-to-run"

[[exemptions.plotters-svg]]
version = "0.3.7"
criteria = "safe-to-run"

[[exemptions.proc-macro2]]
version = "1.0.95"
criteria = "safe-to-deploy"

[[exemptions.quote]]
version = "1.0.40"
criteria = "safe-to-deploy"

[[exemptions.r-efi]]
version = "5.2.0"
criteria = "safe-to-run"

[[exemptions.rayon]]
version = "1.11.0"
criteria = "safe-to-deploy"

[[exemptions.rayon-core]]
version = "1.13.0"
criteria = "safe-to-deploy"

[[exemptions.redox_users]]
version = "0.5.0"
criteria = "safe-to-deploy"

[[exemptions.regex]]
version = "1.11.1"
criteria = "safe-to-run"

[[exemptions.regex-automata]]
version = "0.4.9"
criteria = "safe-to-run"

[[exemptions.regex-syntax]]
version = "0.8.5"
criteria = "safe-to-run"

[[exemptions.rust-ini]]
version = "0.21.3"
criteria = "safe-to-deploy"

[[exemptions.rustix]]
version = "1.0.5"
criteria = "safe-to-run"

[[exemptions.rustversion]]
version = "1.0.20"
criteria = "safe-to-run"

[[exemptions.ryu]]
version = "1.0.20"
criteria = "safe-to-run"

[[exemptions.same-file]]
version = "1.0.6"
criteria = "safe-to-run"

[[exemptions.serde]]
version = "1.0.219"
criteria = "safe-to-run"

[[exemptions.serde_derive]]
version = "1.0.219"
criteria = "safe-to-run"

[[exemptions.serde_json]]
version = "1.0.140"
criteria = "safe-to-run"

[[exemptions.sha2]]
version = "0.10.8"
criteria = "safe-to-deploy"

[[exemptions.syn]]
version = "2.0.101"
criteria = "safe-to-deploy"

[[exemptions.tempfile]]
version = "3.22.0"
criteria = "safe-to-run"

[[exemptions.thiserror]]
version = "1.0.69"
criteria = "safe-to-deploy"

[[exemptions.thiserror]]
version = "2.0.12"
criteria = "safe-to-deploy"

[[exemptions.thiserror-impl]]
version = "1.0.69"
criteria = "safe-to-deploy"

[[exemptions.thiserror-impl]]
version = "2.0.12"
criteria = "safe-to-deploy"

[[exemptions.tiny-keccak]]
version = "2.0.2"
criteria = "safe-to-deploy"

[[exemptions.tinytemplate]]
version = "1.2.1"
criteria = "safe-to-run"

[[exemptions.typenum]]
version = "1.18.0"
criteria = "safe-to-deploy"

[[exemptions.ucd-trie]]
version = "0.1.7"
criteria = "safe-to-deploy"

[[exemptions.unicase]]
version = "2.8.1"
criteria = "safe-to-deploy"

[[exemptions.unicode-ident]]
version = "1.0.18"
criteria = "safe-to-deploy"

[[exemptions.version_check]]
version = "0.9.5"
criteria = "safe-to-deploy"

[[exemptions.walkdir]]
version = "2.5.0"
criteria = "safe-to-run"

[[exemptions.wasi]]
version = "0.11.0+wasi-snapshot-preview1"
criteria = "safe-to-deploy"

[[exemptions.wasi]]
version = "0.14.2+wasi-0.2.4"
criteria = "safe-to-run"

[[exemptions.wasm-bindgen]]
version = "0.2.100"
criteria = "safe-to-run"

[[exemptions.wasm-bindgen-backend]]
version = "0.2.100"
criteria = "safe-to-run"

[[exemptions.wasm-bindgen-macro]]
version = "0.2.100"
criteria = "safe-to-run"

[[exemptions.wasm-bindgen-macro-support]]
version = "0.2.100"
criteria = "safe-to-run"

[[exemptions.wasm-bindgen-shared]]
version = "0.2.100"
criteria = "safe-to-run"

[[exemptions.web-sys]]
version = "0.3.77"
criteria = "safe-to-run"

[[exemptions.winapi-util]]
version = "0.1.9"
criteria = "safe-to-run"

[[exemptions.windows]]
version = "0.62.0"
criteria = "safe-to-deploy"

[[exemptions.windows-collections]]
version = "0.3.0"
criteria = "safe-to-deploy"

[[exemptions.windows-core]]
version = "0.62.0"
criteria = "safe-to-deploy"

[[exemptions.windows-future]]
version = "0.3.0"
criteria = "safe-to-deploy"

[[exemptions.windows-implement]]
version = "0.60.0"
criteria = "safe-to-deploy"

[[exemptions.windows-interface]]
version = "0.59.1"
criteria = "safe-to-deploy"

[[exemptions.windows-link]]
version = "0.2.0"
criteria = "safe-to-deploy"

[[exemptions.windows-numerics]]
version = "0.3.0"
criteria = "safe-to-deploy"

[[exemptions.windows-result]]
version = "0.4.0"
criteria = "safe-to-deploy"

[[exemptions.windows-strings]]
version = "0.5.0"
criteria = "safe-to-deploy"

[[exemptions.windows-sys]]
version = "0.59.0"
criteria = "safe-to-deploy"

[[exemptions.windows-targets]]
version = "0.52.6"
criteria = "safe-to-deploy"

[[exemptions.windows-threading]]
version = "0.2.0"
criteria = "safe-to-deploy"

[[exemptions.windows_aarch64_gnullvm]]
version = "0.52.6"
criteria = "safe-to-deploy"

[[exemptions.windows_aarch64_msvc]]
version = "0.52.6"
criteria = "safe-to-deploy"

[[exemptions.windows_i686_gnu]]
version = "0.52.6"
criteria = "safe-to-deploy"

[[exemptions.windows_i686_gnullvm]]
version = "0.52.6"
criteria = "safe-to-deploy"

[[exemptions.windows_i686_msvc]]
version = "0.52.6"
criteria = "safe-to-deploy"

[[exemptions.windows_x86_64_gnu]]
version = "0.52.6"
criteria = "safe-to-deploy"

[[exemptions.windows_x86_64_gnullvm]]
version = "0.52.6"
criteria = "safe-to-deploy"

[[exemptions.windows_x86_64_msvc]]
version = "0.52.6"
criteria = "safe-to-deploy"

[[exemptions.wit-bindgen-rt]]
version = "0.39.0"
criteria = "safe-to-run"
