name: Publish to crates.io

on:
  push:
    tags: ['*.*.*']

jobs:
  publish:
    runs-on: ubuntu-24.04

    environment: release

    permissions:
      id-token: write

    steps:
      - uses: actions/checkout@v5

      - uses: rust-lang/crates-io-auth-action@041cce5b4b821e6b0ebc9c9c38b58cac4e34dcc2 # v1.0.2
        id: auth

      - run: cargo publish
        env:
          CARGO_REGISTRY_TOKEN: ${{ steps.auth.outputs.token }}
